---
version: "2.1"
services:
  minetest:
    image: ghcr.io/linuxserver/minetest:latest
    container_name: minetest_tutorial
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CLI_ARGS=" --worldname KidsLab --world worlds --port 30000"
    volumes:
      - .:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped

